spring:
    application:
        name: @project.artifactId@

jwt.auth:
  appName: sampleapp
  keyStore: classpath:sample.jks
  enabled: false
  storePassword: sample
  keyPassword: sample
  alias: sample
  algo: RSA
  secret: 'XqLe/s1jnJBLnz8HoiBelfbY9H+qG0jouds5cAEKucc='
  trustedAppKeys:
    sampleapp: sample
  excludePath: ['/hello/**', '/_manage/**']

management.context-path: /_manage
